export const LocalResources = {
  TabIcons: {
    ic_tab_add: require('../assets/tab_icons/ic_tab_add.png'),
    ic_tab_explore: require('../assets/tab_icons/ic_tab_explore.png'),
    ic_tab_explore_selected: require('../assets/tab_icons/ic_tab_explore_selected.png'),
    ic_tab_fav: require('../assets/tab_icons/ic_tab_fav.png'),
    ic_tab_fav_selected: require('../assets/tab_icons/ic_tab_fav_selected.png'),
    ic_tab_home: require('../assets/tab_icons/ic_tab_home.png'),
    ic_tab_home_selected: require('../assets/tab_icons/ic_tab_home_selected.png'),
    ic_tab_profile: require('../assets/tab_icons/ic_tab_profile.png'),
    ic_tab_profile_selected: require('../assets/tab_icons/ic_tab_profile_selected.png'),
  },
  Icons: {
    ic_clear_text_input: require('../assets/ic_clear_text_input.png'),
    ic_eye_hidden: require('../assets/ic_eye_hidden.png'),
    ic_eye_visible: require('../assets/ic_eye_visible.png'),
    ic_message: require('../assets/ic_message.png'),
    ic_post_comment: require('../assets/ic_post_comment.png'),
    ic_post_direct: require('../assets/ic_post_direct.png'),
    ic_post_like: require('../assets/ic_post_like.png'),
    ic_post_like_selected: require('../assets/ic_post_like_selected.png'),
    ic_post_more: require('../assets/ic_post_more.png'),
    ic_post_save: require('../assets/ic_post_save.png'),
    ic_post_save_selected: require('../assets/ic_post_save_selected.png'),
    ic_refresh: require('../assets/ic_refresh.png'),
    ic_search: require('../assets/ic_search.png'),
    ic_signup_user: require('../assets/ic_signup_user.png'),
    ic_warning: require('../assets/ic_warning.png'),
    ic_grid: require('../assets/ic_grid.png'),
    ic_story_add: require('../assets/ic_story_add.png'),
    ic_reel: require('../assets/ic_reel.png'),
    ic_live: require('../assets/ic_live.png'),
  },
  Images: {
    instagram_text: require('../assets/instagram_text.png'),
    logo_fb_rounded: require('../assets/logo_fb_rounded.png'),
  },
  Fonts: {},
};
